---
- :section: first_name
  :fields:
    :person:
      :first_name:
        :required: true
        :lead_required: true
        :disabled: if_preapproved
        :order: 10
- :section: last_name
  :fields:
    :person:
      :last_name:
        :required: true
        :lead_required: true
        :disabled: if_preapproved
        :order: 10
- :section: email
  :fields:
    :customer:
      :email:
        :required: true
        :lead_required: true
        :validation: email
        :order: 10
- :section: street_address
  :fields:
    :customer_address:
      :address_1:
        :required: true
        :lead_required: true
        :disabled: if_preapproved
        :order: 10
      :address_2:
        :required: false
        :disabled: if_preapproved
        :order: 20
- :section: city
  :fields:
    :customer_address:
      :city:
        :required: true
        :validation: regex
        :parameter: "^([a-zA-Z\x80-ɏ]+(?:. |-| |'))*[a-zA-Z\x80-ɏ]*$"
        :lead_required: true
        :disabled: if_preapproved
        :order: 10
- :section: state
  :fields:
    :customer_address:
      :state:
        :required: true
        :validation: not_null
        :lead_required: true
        :disabled: if_preapproved
        :order: 10
- :section: zip
  :fields:
    :customer_address:
      :zip:
        :required: true
        :lead_required: true
        :disabled: if_preapproved
        :order: 10
- :section: military_address
  :fields:
    :customer_address:
      :military_region:
        :required: if_military_address
        :order: 10
      :military_address:
        :required: false
        :order: 20
- :section: date_of_birth
  :fields:
    :person:
      :date_of_birth:
        :required: false
        :lead_required: true
        :order: 10
      :date_of_birth_month:
        :required: true
        :validation: not_null
        :order: 20
      :date_of_birth_day:
        :required: true
        :validation: not_null
        :order: 30
      :date_of_birth_year:
        :required: true
        :validation: not_null
        :order: 40
- :section: phone
  :fields:
    :person:
      :home_phone:
        :required: true
        :lead_required: true
        :validation: regex
        :parameter: "^\\s*(?:\\+?(\\d{1,3}))?[-. (]*(\\d{3})[-. )]*(\\d{3})[-. ]*(\\d{4})(?:
          *x(\\d+))?\\s*$"
        :order: 10
- :section: income_type
  :fields:
    :income:
      :income_type:
        :required: true
        :lead_required: true
        :order: 10
- :section: monthly_net_income
  :fields:
    :income:
      :monthly_net_income:
        :required: true
        :validation: regex
        :parameter: "^[0-9.,]+$"
        :lead_required: true
        :order: 10
- :section: ssn
  :fields:
    :person:
      :ssn:
        :required: true
        :validation: regex
        :parameter: "^[0-9]{9}$"
        :lead_required: true
        :order: 10
- :section: password
  :fields:
    :customer:
      :password:
        :required: true
        :parameter: 6
        :validation: min_length
        :persist: false
        :order: 10
      :password_confirmation:
        :required: matching_password
        :validation: matches_field
        :parameter: customer.password
        :persist: false
        :order: 20
- :section: hear_about_us
  :fields:
    :customer_application_metadata:
      :acquisition_channel:
        :required: false
        :order: 10
- :section: promotions
  :fields:
    :customer_application_metadata:
      :promo_code:
        :required: false
        :order: 10
- :section: main
  :fields:
    :customer_consent:
      :nm_consumer_information:
        :required: if_customer_certain_state
        :state: NM
        :checkbox: true
      :il_consumer_information:
        :required: if_customer_certain_state
        :state: IL
        :checkbox: true
      :de_consumer_information:
        :required: if_customer_certain_state
        :state: DE
        :checkbox: true
      :sc_consumer_information:
        :required: if_customer_certain_state
        :state: SC
        :checkbox: true
    :customer:
      :credit_report_authorization:
        :required: true
        :checkbox: true
      :email_additional_offers:
        :required: false
        :checkbox: true
        :hide: true
      :electronic_communications_consent:
        :required: true
        :checkbox: true
      :privacy_policy_consent:
        :required: true
        :checkbox: true